stages:
  - baseImages
  - buildImages
  - devImages

before_script:
  - apk add --no-cache bash
  - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_ACCESS_TOKEN

php:8.0-fpm:
  stage: baseImages
  image: docker:stable
  services:
    - docker:dind
  script:
    - ./build.sh php:8.0-fpm-alpine liteacz/php:8.0-fpm fpm fpm/base/Dockerfile
  only:
    - tags
    - web

php:8.0-fpm-build:
  stage: buildImages
  image: docker:stable
  services:
    - docker:dind
  script:
    - ./build.sh liteacz/php:8.0-fpm liteacz/php:8.0-fpm-build fpm fpm/build/Dockerfile
  only:
    - tags
    - web

php:8.0-fpm-dev:
  stage: devImages
  image: docker:stable
  services:
    - docker:dind
  script:
    - ./build.sh liteacz/php:8.0-fpm-build liteacz/php:8.0-fpm-dev fpm fpm/dev/Dockerfile
  only:
    - tags
    - web

php:8.0-cli:
  stage: baseImages
  image: docker:stable
  services:
    - docker:dind
  script:
    - ./build.sh php:8.0-cli-alpine liteacz/php:8.0-cli cli cli/base/Dockerfile
  only:
    - tags
    - web

php:8.0-cli-build:
  stage: buildImages
  image: docker:stable
  services:
    - docker:dind
  script:
    - ./build.sh liteacz/php:8.0-cli liteacz/php:8.0-cli-build cli cli/build/Dockerfile
  only:
    - tags
    - web

php:8.0-cli-dev:
  stage: devImages
  image: docker:stable
  services:
    - docker:dind
  script:
    - ./build.sh liteacz/php:8.0-cli-build liteacz/php:8.0-cli-dev cli cli/dev/Dockerfile
  only:
    - tags
    - web